#!/bin/bash

helpFunction()
{
   echo ""
   echo "Usage: $0 -d TWITTER_DATA_FILE -g MELBGRID_FILE [-options]"
   echo "Options include:"
   echo -e "\t-d\tPath to twitter data file <REQUIRE>"
   echo -e "\t-g\tPath to melbourne grid file <REQUIRE>"
   echo -e "\t-c\tMaximum number of tasks/CPU cores used by the job\t(default: 1)"
   echo -e "\t-e\tEmail for finish notification\t(default: xuwang2@student.unimelb.edu.au)"
   echo -e "\t-n\tNumber of nodes\t(default: 1)"
   echo -e "\t-?\tPrint this help message"
   echo ""
   exit 1 # Exit script after printing help
}

while getopts "c:d:e:g:n:" opt
do
   case "$opt" in
      c ) CORE_NUMBER="$OPTARG" ;;
      d ) TWITTER_DATA_FILE="$OPTARG" ;;
      e ) EMAIL="$OPTARG" ;;
      g ) MELBGRID_FILE="$OPTARG" ;;
      n ) NODE_NUMBER="$OPTARG" ;;
      ? ) helpFunction ;;
   esac
done

# Print helpFunction in case parameters are empty
#if [ -z "$TWITTER_DATA_FILE" ] || [ -z "$MELBGRID_FILE" ]
#then
#   echo "Some or all of the parameters are empty";
#   helpFunction
#fi

#link json files to data/
bigTwitter="$PWD/../data/bigTwitter.json"
smallTwitter="$PWD/../data/smallTwitter.json"
tinyTwitter="$PWD/../data/tinyTwitter.json"
melbGrid="$PWD/../data/melbGrid.json"
if [ ! -d "$PWD/../data" ]
then
   mkdir "$PWD/../data"
   ln -s /data/projects/COMP90024/bigTwitter.json
   ln -s /data/projects/COMP90024/smallTwitter.json
   ln -s /data/projects/COMP90024/tinyTwitter.json
   ln -s /data/projects/COMP90024/melbGrid.json
elif [ ! -f "$bigTwitter" ]
then
   cd ../data
   ln -s /data/projects/COMP90024/bigTwitter.json
   cd -
   echo "============= Linked bigTwitter.json ================="
elif [ ! -f "$smallTwitter" ]
then
   cd ../data
   ln -s /data/projects/COMP90024/smallTwitter.json
   cd -
   echo "============= Linked smallTwitter.json ================="
elif [ ! -f "$tinyTwitter" ]
then
   cd ../data
   ln -s /data/projects/COMP90024/tinyTwitter.json
   cd -
   echo "============= Linked tinyTwitter.json ================="
elif [ ! -f "$melbGrid" ]
then
   cd ../data
   ln -s /data/projects/COMP90024/melbGrid.json
   cd -
   echo "============= Linked melbGrid.json ================="
fi

# load modules
echo "============= Start Loading Modules =================="
module load Python/3.5.2-GCC-6.2.0
module load MPICH/3.2.1-GCC-6.2.0
echo "============= Load Modules Succesful! ================"

#install dependencies
echo "============= Start Installing Dependencies =========="
pip3 install --user mpi4py
echo "============= Install Dependencies Succesful! ========"

export CORE_NUMBER
export NODE_NUMBER
export TWITTER_DATA_FILE
export MELBGRID_FILE
export EMAIL

#start slurm script
source scripts/sbatch
