#!/bin/sh

helpFunction()
{
   echo ""
   echo "Usage: $0 -f YOUR_FILE_NAME"
   echo "====================================="
   echo "=          Example Command          ="
   echo "====================================="
   echo "=    ./run -f 1core_1node_tiny      ="
   echo "=    ./run -f 8core_1node_tiny      ="
   echo "====================================="
   echo ""
   exit 1 # Exit script after printing help
}

while getopts "f:" opt
do
   case "$opt" in
      f ) YOUR_FILE_NAME="$OPTARG" ;;
      ? ) helpFunction ;;
   esac
done

# Print helpFunction in case parameters are empty
if [ -z "$YOUR_FILE_NAME" ]
then
   echo "Some or all of the parameters are empty";
   helpFunction
fi

#link json files to data/
bigTwitter="$PWD/data/bigTwitter.json"
if [ ! -f "$bigTwitter" ]; then
   cd data/
   ln -s /data/projects/COMP90024/bigTwitter.json
   cd -
   echo "============= Linked bigTwitter.json ================="
fi

# load modules
echo "============= Start Loading Modules =================="
module load Python/3.5.2-GCC-6.2.0
module load MPICH/3.2.1-GCC-6.2.0
echo "============= Load Modules Succesful! ================"

#install dependencies
echo "============= Start Installing Dependencies =========="
pip3 install --user mpi4py
pip3 install --user ijson
echo "============= Install Dependencies Succesful! ========"

#start slurm script
echo "============= Your current path is $PWD =============="
sbatch --partition cloud $PWD/slurm/$YOUR_FILE_NAME.slurm
